// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "nerons.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic nerons::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic nerons::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<33> nerons::ap_ST_fsm_state1 = "1";
const sc_lv<33> nerons::ap_ST_fsm_state2 = "10";
const sc_lv<33> nerons::ap_ST_fsm_state3 = "100";
const sc_lv<33> nerons::ap_ST_fsm_state4 = "1000";
const sc_lv<33> nerons::ap_ST_fsm_state5 = "10000";
const sc_lv<33> nerons::ap_ST_fsm_state6 = "100000";
const sc_lv<33> nerons::ap_ST_fsm_state7 = "1000000";
const sc_lv<33> nerons::ap_ST_fsm_state8 = "10000000";
const sc_lv<33> nerons::ap_ST_fsm_state9 = "100000000";
const sc_lv<33> nerons::ap_ST_fsm_state10 = "1000000000";
const sc_lv<33> nerons::ap_ST_fsm_state11 = "10000000000";
const sc_lv<33> nerons::ap_ST_fsm_state12 = "100000000000";
const sc_lv<33> nerons::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<33> nerons::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<33> nerons::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<33> nerons::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<33> nerons::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<33> nerons::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<33> nerons::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<33> nerons::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<33> nerons::ap_ST_fsm_state21 = "100000000000000000000";
const sc_lv<33> nerons::ap_ST_fsm_state22 = "1000000000000000000000";
const sc_lv<33> nerons::ap_ST_fsm_state23 = "10000000000000000000000";
const sc_lv<33> nerons::ap_ST_fsm_state24 = "100000000000000000000000";
const sc_lv<33> nerons::ap_ST_fsm_state25 = "1000000000000000000000000";
const sc_lv<33> nerons::ap_ST_fsm_state26 = "10000000000000000000000000";
const sc_lv<33> nerons::ap_ST_fsm_state27 = "100000000000000000000000000";
const sc_lv<33> nerons::ap_ST_fsm_state28 = "1000000000000000000000000000";
const sc_lv<33> nerons::ap_ST_fsm_state29 = "10000000000000000000000000000";
const sc_lv<33> nerons::ap_ST_fsm_state30 = "100000000000000000000000000000";
const sc_lv<33> nerons::ap_ST_fsm_state31 = "1000000000000000000000000000000";
const sc_lv<33> nerons::ap_ST_fsm_state32 = "10000000000000000000000000000000";
const sc_lv<33> nerons::ap_ST_fsm_state33 = "100000000000000000000000000000000";
const sc_lv<32> nerons::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> nerons::ap_const_lv32_17 = "10111";
const sc_lv<32> nerons::ap_const_lv32_1F = "11111";
const sc_lv<32> nerons::ap_const_lv32_4 = "100";
const sc_lv<32> nerons::ap_const_lv32_5 = "101";
const sc_lv<32> nerons::ap_const_lv32_6 = "110";
const sc_lv<32> nerons::ap_const_lv32_7 = "111";
const sc_lv<32> nerons::ap_const_lv32_B = "1011";
const sc_lv<32> nerons::ap_const_lv32_10 = "10000";
const sc_lv<32> nerons::ap_const_lv32_11 = "10001";
const sc_lv<32> nerons::ap_const_lv32_19 = "11001";
const sc_lv<4> nerons::ap_const_lv4_0 = "0000";
const sc_lv<32> nerons::ap_const_lv32_3 = "11";
const sc_lv<32> nerons::ap_const_lv32_20 = "100000";
const sc_lv<10> nerons::ap_const_lv10_0 = "0000000000";
const sc_lv<7> nerons::ap_const_lv7_0 = "0000000";
const sc_lv<32> nerons::ap_const_lv32_1 = "1";
const sc_lv<32> nerons::ap_const_lv32_2 = "10";
const sc_lv<32> nerons::ap_const_lv32_18 = "11000";
const sc_lv<64> nerons::ap_const_lv64_3FE55555571F7693 = "11111111100101010101010101010101010111000111110111011010010011";
const sc_lv<64> nerons::ap_const_lv64_3FFB74538EF34D6A = "11111111111011011101000101001110001110111100110100110101101010";
const sc_lv<32> nerons::ap_const_lv32_12 = "10010";
const sc_lv<32> nerons::ap_const_lv32_1A = "11010";
const sc_lv<32> nerons::ap_const_lv32_C = "1100";
const sc_lv<32> nerons::ap_const_lv32_8 = "1000";
const sc_lv<10> nerons::ap_const_lv10_65 = "1100101";
const sc_lv<4> nerons::ap_const_lv4_A = "1010";
const sc_lv<4> nerons::ap_const_lv4_1 = "1";
const sc_lv<7> nerons::ap_const_lv7_64 = "1100100";
const sc_lv<7> nerons::ap_const_lv7_1 = "1";
const sc_lv<1> nerons::ap_const_lv1_1 = "1";
const bool nerons::ap_const_boolean_1 = true;

nerons::nerons(sc_module_name name) : sc_module(name), mVcdFile(0) {
    Layer4_Weights_CPU_U = new nerons_Layer4_Weights_CPU("Layer4_Weights_CPU_U");
    Layer4_Weights_CPU_U->clk(ap_clk);
    Layer4_Weights_CPU_U->reset(ap_rst);
    Layer4_Weights_CPU_U->address0(Layer4_Weights_CPU_address0);
    Layer4_Weights_CPU_U->ce0(Layer4_Weights_CPU_ce0);
    Layer4_Weights_CPU_U->q0(Layer4_Weights_CPU_q0);
    Layer3_Neurons_CPU_U = new nerons_Layer3_Neurons_CPU("Layer3_Neurons_CPU_U");
    Layer3_Neurons_CPU_U->clk(ap_clk);
    Layer3_Neurons_CPU_U->reset(ap_rst);
    Layer3_Neurons_CPU_U->address0(Layer3_Neurons_CPU_address0);
    Layer3_Neurons_CPU_U->ce0(Layer3_Neurons_CPU_ce0);
    Layer3_Neurons_CPU_U->we0(Layer3_Neurons_CPU_we0);
    Layer3_Neurons_CPU_U->d0(grp_calculateLayer3_fu_157_Layer3_Neurons_CPU_d0);
    Layer3_Neurons_CPU_U->q0(Layer3_Neurons_CPU_q0);
    Layer4_Neurons_CPU_U = new nerons_Layer4_Neurons_CPU("Layer4_Neurons_CPU_U");
    Layer4_Neurons_CPU_U->clk(ap_clk);
    Layer4_Neurons_CPU_U->reset(ap_rst);
    Layer4_Neurons_CPU_U->address0(Layer4_Neurons_CPU_address0);
    Layer4_Neurons_CPU_U->ce0(Layer4_Neurons_CPU_ce0);
    Layer4_Neurons_CPU_U->we0(Layer4_Neurons_CPU_we0);
    Layer4_Neurons_CPU_U->d0(grp_calculateLayer4_fu_173_Layer4_Neurons_CPU_d0);
    Layer4_Neurons_CPU_U->q0(Layer4_Neurons_CPU_q0);
    grp_calculateLayer3_fu_157 = new calculateLayer3("grp_calculateLayer3_fu_157");
    grp_calculateLayer3_fu_157->ap_clk(ap_clk);
    grp_calculateLayer3_fu_157->ap_rst(ap_rst);
    grp_calculateLayer3_fu_157->ap_start(grp_calculateLayer3_fu_157_ap_start);
    grp_calculateLayer3_fu_157->ap_done(grp_calculateLayer3_fu_157_ap_done);
    grp_calculateLayer3_fu_157->ap_idle(grp_calculateLayer3_fu_157_ap_idle);
    grp_calculateLayer3_fu_157->ap_ready(grp_calculateLayer3_fu_157_ap_ready);
    grp_calculateLayer3_fu_157->Layer2_Neurons_CPU_address0(grp_calculateLayer3_fu_157_Layer2_Neurons_CPU_address0);
    grp_calculateLayer3_fu_157->Layer2_Neurons_CPU_ce0(grp_calculateLayer3_fu_157_Layer2_Neurons_CPU_ce0);
    grp_calculateLayer3_fu_157->Layer2_Neurons_CPU_q0(Layer2_Neurons_CPU_q0);
    grp_calculateLayer3_fu_157->Layer2_Neurons_CPU_address1(grp_calculateLayer3_fu_157_Layer2_Neurons_CPU_address1);
    grp_calculateLayer3_fu_157->Layer2_Neurons_CPU_ce1(grp_calculateLayer3_fu_157_Layer2_Neurons_CPU_ce1);
    grp_calculateLayer3_fu_157->Layer2_Neurons_CPU_q1(Layer2_Neurons_CPU_q1);
    grp_calculateLayer3_fu_157->Layer3_Neurons_CPU_address0(grp_calculateLayer3_fu_157_Layer3_Neurons_CPU_address0);
    grp_calculateLayer3_fu_157->Layer3_Neurons_CPU_ce0(grp_calculateLayer3_fu_157_Layer3_Neurons_CPU_ce0);
    grp_calculateLayer3_fu_157->Layer3_Neurons_CPU_we0(grp_calculateLayer3_fu_157_Layer3_Neurons_CPU_we0);
    grp_calculateLayer3_fu_157->Layer3_Neurons_CPU_d0(grp_calculateLayer3_fu_157_Layer3_Neurons_CPU_d0);
    grp_calculateLayer4_fu_173 = new calculateLayer4("grp_calculateLayer4_fu_173");
    grp_calculateLayer4_fu_173->ap_clk(ap_clk);
    grp_calculateLayer4_fu_173->ap_rst(ap_rst);
    grp_calculateLayer4_fu_173->ap_start(grp_calculateLayer4_fu_173_ap_start);
    grp_calculateLayer4_fu_173->ap_done(grp_calculateLayer4_fu_173_ap_done);
    grp_calculateLayer4_fu_173->ap_idle(grp_calculateLayer4_fu_173_ap_idle);
    grp_calculateLayer4_fu_173->ap_ready(grp_calculateLayer4_fu_173_ap_ready);
    grp_calculateLayer4_fu_173->Layer3_Neurons_CPU_address0(grp_calculateLayer4_fu_173_Layer3_Neurons_CPU_address0);
    grp_calculateLayer4_fu_173->Layer3_Neurons_CPU_ce0(grp_calculateLayer4_fu_173_Layer3_Neurons_CPU_ce0);
    grp_calculateLayer4_fu_173->Layer3_Neurons_CPU_q0(Layer3_Neurons_CPU_q0);
    grp_calculateLayer4_fu_173->Layer4_Neurons_CPU_address0(grp_calculateLayer4_fu_173_Layer4_Neurons_CPU_address0);
    grp_calculateLayer4_fu_173->Layer4_Neurons_CPU_ce0(grp_calculateLayer4_fu_173_Layer4_Neurons_CPU_ce0);
    grp_calculateLayer4_fu_173->Layer4_Neurons_CPU_we0(grp_calculateLayer4_fu_173_Layer4_Neurons_CPU_we0);
    grp_calculateLayer4_fu_173->Layer4_Neurons_CPU_d0(grp_calculateLayer4_fu_173_Layer4_Neurons_CPU_d0);
    grp_generic_tanh_double_s_fu_187 = new generic_tanh_double_s("grp_generic_tanh_double_s_fu_187");
    grp_generic_tanh_double_s_fu_187->ap_clk(ap_clk);
    grp_generic_tanh_double_s_fu_187->ap_rst(ap_rst);
    grp_generic_tanh_double_s_fu_187->ap_start(grp_generic_tanh_double_s_fu_187_ap_start);
    grp_generic_tanh_double_s_fu_187->ap_done(grp_generic_tanh_double_s_fu_187_ap_done);
    grp_generic_tanh_double_s_fu_187->ap_idle(grp_generic_tanh_double_s_fu_187_ap_idle);
    grp_generic_tanh_double_s_fu_187->ap_ready(grp_generic_tanh_double_s_fu_187_ap_ready);
    grp_generic_tanh_double_s_fu_187->t_in(reg_217);
    grp_generic_tanh_double_s_fu_187->ap_return(grp_generic_tanh_double_s_fu_187_ap_return);
    nerons_dmul_64ns_64ns_64_6_max_dsp_1_U46 = new nerons_dmul_64ns_64ns_64_6_max_dsp_1<1,6,64,64,64>("nerons_dmul_64ns_64ns_64_6_max_dsp_1_U46");
    nerons_dmul_64ns_64ns_64_6_max_dsp_1_U46->clk(ap_clk);
    nerons_dmul_64ns_64ns_64_6_max_dsp_1_U46->reset(ap_rst);
    nerons_dmul_64ns_64ns_64_6_max_dsp_1_U46->din0(grp_fu_198_p0);
    nerons_dmul_64ns_64ns_64_6_max_dsp_1_U46->din1(grp_fu_198_p1);
    nerons_dmul_64ns_64ns_64_6_max_dsp_1_U46->ce(ap_var_for_const0);
    nerons_dmul_64ns_64ns_64_6_max_dsp_1_U46->dout(grp_fu_198_p2);
    nerons_hadd_16ns_16ns_16_5_full_dsp_1_U47 = new nerons_hadd_16ns_16ns_16_5_full_dsp_1<1,5,16,16,16>("nerons_hadd_16ns_16ns_16_5_full_dsp_1_U47");
    nerons_hadd_16ns_16ns_16_5_full_dsp_1_U47->clk(ap_clk);
    nerons_hadd_16ns_16ns_16_5_full_dsp_1_U47->reset(ap_rst);
    nerons_hadd_16ns_16ns_16_5_full_dsp_1_U47->din0(somme_0_i_reg_136);
    nerons_hadd_16ns_16ns_16_5_full_dsp_1_U47->din1(tmp_3_i_reg_334);
    nerons_hadd_16ns_16ns_16_5_full_dsp_1_U47->ce(ap_var_for_const0);
    nerons_hadd_16ns_16ns_16_5_full_dsp_1_U47->dout(grp_fu_204_p2);
    nerons_hmul_16ns_16ns_16_4_max_dsp_1_U48 = new nerons_hmul_16ns_16ns_16_4_max_dsp_1<1,4,16,16,16>("nerons_hmul_16ns_16ns_16_4_max_dsp_1_U48");
    nerons_hmul_16ns_16ns_16_4_max_dsp_1_U48->clk(ap_clk);
    nerons_hmul_16ns_16ns_16_4_max_dsp_1_U48->reset(ap_rst);
    nerons_hmul_16ns_16ns_16_4_max_dsp_1_U48->din0(Layer4_Weights_CPU_l_reg_324);
    nerons_hmul_16ns_16ns_16_4_max_dsp_1_U48->din1(Layer4_Neurons_CPU_l_reg_329);
    nerons_hmul_16ns_16ns_16_4_max_dsp_1_U48->ce(ap_var_for_const0);
    nerons_hmul_16ns_16ns_16_4_max_dsp_1_U48->dout(grp_fu_209_p2);
    nerons_hptodp_16ns_64_2_1_U49 = new nerons_hptodp_16ns_64_2_1<1,2,16,64>("nerons_hptodp_16ns_64_2_1_U49");
    nerons_hptodp_16ns_64_2_1_U49->clk(ap_clk);
    nerons_hptodp_16ns_64_2_1_U49->reset(ap_rst);
    nerons_hptodp_16ns_64_2_1_U49->din0(somme_0_i_reg_136);
    nerons_hptodp_16ns_64_2_1_U49->ce(ap_var_for_const0);
    nerons_hptodp_16ns_64_2_1_U49->dout(grp_fu_213_p1);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_Layer2_Neurons_CPU_address0);
    sensitive << ( grp_calculateLayer3_fu_157_Layer2_Neurons_CPU_address0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_Layer2_Neurons_CPU_address1);
    sensitive << ( grp_calculateLayer3_fu_157_Layer2_Neurons_CPU_address1 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_Layer2_Neurons_CPU_ce0);
    sensitive << ( grp_calculateLayer3_fu_157_Layer2_Neurons_CPU_ce0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_Layer2_Neurons_CPU_ce1);
    sensitive << ( grp_calculateLayer3_fu_157_Layer2_Neurons_CPU_ce1 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_Layer3_Neurons_CPU_address0);
    sensitive << ( grp_calculateLayer3_fu_157_Layer3_Neurons_CPU_address0 );
    sensitive << ( grp_calculateLayer4_fu_173_Layer3_Neurons_CPU_address0 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_Layer3_Neurons_CPU_ce0);
    sensitive << ( grp_calculateLayer3_fu_157_Layer3_Neurons_CPU_ce0 );
    sensitive << ( grp_calculateLayer4_fu_173_Layer3_Neurons_CPU_ce0 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_Layer3_Neurons_CPU_we0);
    sensitive << ( grp_calculateLayer3_fu_157_Layer3_Neurons_CPU_we0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_Layer4_Neurons_CPU_address0);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( grp_calculateLayer4_fu_173_Layer4_Neurons_CPU_address0 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( zext_ln60_1_fu_273_p1 );

    SC_METHOD(thread_Layer4_Neurons_CPU_ce0);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( grp_calculateLayer4_fu_173_Layer4_Neurons_CPU_ce0 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_Layer4_Neurons_CPU_we0);
    sensitive << ( grp_calculateLayer4_fu_173_Layer4_Neurons_CPU_we0 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_Layer4_Weights_CPU_address0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( zext_ln58_fu_241_p1 );
    sensitive << ( zext_ln60_fu_268_p1 );

    SC_METHOD(thread_Layer4_Weights_CPU_ce0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_Layer5_Neurons_CPU_address0);
    sensitive << ( ap_CS_fsm_state33 );
    sensitive << ( zext_ln61_fu_278_p1 );

    SC_METHOD(thread_Layer5_Neurons_CPU_ce0);
    sensitive << ( ap_CS_fsm_state33 );

    SC_METHOD(thread_Layer5_Neurons_CPU_d0);
    sensitive << ( reg_217 );
    sensitive << ( ap_CS_fsm_state33 );

    SC_METHOD(thread_Layer5_Neurons_CPU_we0);
    sensitive << ( ap_CS_fsm_state33 );

    SC_METHOD(thread_add_ln57_fu_223_p2);
    sensitive << ( phi_mul_reg_124 );

    SC_METHOD(thread_add_ln60_1_fu_262_p2);
    sensitive << ( phi_mul_reg_124 );
    sensitive << ( zext_ln60_2_fu_258_p1 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state17);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state18);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state19);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state24);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state25);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state26);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state27);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state32);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state33);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln57_fu_229_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln57_fu_229_p2 );

    SC_METHOD(thread_grp_calculateLayer3_fu_157_ap_start);
    sensitive << ( grp_calculateLayer3_fu_157_ap_start_reg );

    SC_METHOD(thread_grp_calculateLayer4_fu_173_ap_start);
    sensitive << ( grp_calculateLayer4_fu_173_ap_start_reg );

    SC_METHOD(thread_grp_fu_198_p0);
    sensitive << ( tmp_i_reg_344 );
    sensitive << ( tmp_i_i_reg_349 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( ap_CS_fsm_state27 );

    SC_METHOD(thread_grp_fu_198_p1);
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( ap_CS_fsm_state27 );

    SC_METHOD(thread_grp_generic_tanh_double_s_fu_187_ap_start);
    sensitive << ( grp_generic_tanh_double_s_fu_187_ap_start_reg );

    SC_METHOD(thread_i_fu_235_p2);
    sensitive << ( i_0_i_reg_112 );

    SC_METHOD(thread_icmp_ln57_fu_229_p2);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( i_0_i_reg_112 );

    SC_METHOD(thread_icmp_ln59_fu_246_p2);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( j_0_i_reg_146 );

    SC_METHOD(thread_j_fu_252_p2);
    sensitive << ( j_0_i_reg_146 );

    SC_METHOD(thread_zext_ln58_fu_241_p1);
    sensitive << ( phi_mul_reg_124 );

    SC_METHOD(thread_zext_ln60_1_fu_273_p1);
    sensitive << ( j_0_i_reg_146 );

    SC_METHOD(thread_zext_ln60_2_fu_258_p1);
    sensitive << ( j_fu_252_p2 );

    SC_METHOD(thread_zext_ln60_fu_268_p1);
    sensitive << ( add_ln60_1_fu_262_p2 );

    SC_METHOD(thread_zext_ln61_fu_278_p1);
    sensitive << ( i_0_i_reg_112 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln57_fu_229_p2 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( icmp_ln59_fu_246_p2 );
    sensitive << ( ap_CS_fsm_state26 );
    sensitive << ( grp_generic_tanh_double_s_fu_187_ap_done );
    sensitive << ( grp_calculateLayer3_fu_157_ap_done );
    sensitive << ( grp_calculateLayer4_fu_173_ap_done );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "000000000000000000000000000000001";
    grp_calculateLayer3_fu_157_ap_start_reg = SC_LOGIC_0;
    grp_calculateLayer4_fu_173_ap_start_reg = SC_LOGIC_0;
    grp_generic_tanh_double_s_fu_187_ap_start_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "nerons_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, Layer2_Neurons_CPU_address0, "(port)Layer2_Neurons_CPU_address0");
    sc_trace(mVcdFile, Layer2_Neurons_CPU_ce0, "(port)Layer2_Neurons_CPU_ce0");
    sc_trace(mVcdFile, Layer2_Neurons_CPU_q0, "(port)Layer2_Neurons_CPU_q0");
    sc_trace(mVcdFile, Layer2_Neurons_CPU_address1, "(port)Layer2_Neurons_CPU_address1");
    sc_trace(mVcdFile, Layer2_Neurons_CPU_ce1, "(port)Layer2_Neurons_CPU_ce1");
    sc_trace(mVcdFile, Layer2_Neurons_CPU_q1, "(port)Layer2_Neurons_CPU_q1");
    sc_trace(mVcdFile, Layer5_Neurons_CPU_address0, "(port)Layer5_Neurons_CPU_address0");
    sc_trace(mVcdFile, Layer5_Neurons_CPU_ce0, "(port)Layer5_Neurons_CPU_ce0");
    sc_trace(mVcdFile, Layer5_Neurons_CPU_we0, "(port)Layer5_Neurons_CPU_we0");
    sc_trace(mVcdFile, Layer5_Neurons_CPU_d0, "(port)Layer5_Neurons_CPU_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, Layer4_Weights_CPU_address0, "Layer4_Weights_CPU_address0");
    sc_trace(mVcdFile, Layer4_Weights_CPU_ce0, "Layer4_Weights_CPU_ce0");
    sc_trace(mVcdFile, Layer4_Weights_CPU_q0, "Layer4_Weights_CPU_q0");
    sc_trace(mVcdFile, grp_fu_198_p2, "grp_fu_198_p2");
    sc_trace(mVcdFile, reg_217, "reg_217");
    sc_trace(mVcdFile, ap_CS_fsm_state24, "ap_CS_fsm_state24");
    sc_trace(mVcdFile, ap_CS_fsm_state32, "ap_CS_fsm_state32");
    sc_trace(mVcdFile, add_ln57_fu_223_p2, "add_ln57_fu_223_p2");
    sc_trace(mVcdFile, add_ln57_reg_283, "add_ln57_reg_283");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, i_fu_235_p2, "i_fu_235_p2");
    sc_trace(mVcdFile, i_reg_291, "i_reg_291");
    sc_trace(mVcdFile, icmp_ln57_fu_229_p2, "icmp_ln57_fu_229_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, j_fu_252_p2, "j_fu_252_p2");
    sc_trace(mVcdFile, j_reg_309, "j_reg_309");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, icmp_ln59_fu_246_p2, "icmp_ln59_fu_246_p2");
    sc_trace(mVcdFile, Layer4_Weights_CPU_l_reg_324, "Layer4_Weights_CPU_l_reg_324");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, Layer4_Neurons_CPU_q0, "Layer4_Neurons_CPU_q0");
    sc_trace(mVcdFile, Layer4_Neurons_CPU_l_reg_329, "Layer4_Neurons_CPU_l_reg_329");
    sc_trace(mVcdFile, grp_fu_209_p2, "grp_fu_209_p2");
    sc_trace(mVcdFile, tmp_3_i_reg_334, "tmp_3_i_reg_334");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, grp_fu_204_p2, "grp_fu_204_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state17, "ap_CS_fsm_state17");
    sc_trace(mVcdFile, grp_fu_213_p1, "grp_fu_213_p1");
    sc_trace(mVcdFile, tmp_i_reg_344, "tmp_i_reg_344");
    sc_trace(mVcdFile, ap_CS_fsm_state18, "ap_CS_fsm_state18");
    sc_trace(mVcdFile, grp_generic_tanh_double_s_fu_187_ap_return, "grp_generic_tanh_double_s_fu_187_ap_return");
    sc_trace(mVcdFile, tmp_i_i_reg_349, "tmp_i_i_reg_349");
    sc_trace(mVcdFile, ap_CS_fsm_state26, "ap_CS_fsm_state26");
    sc_trace(mVcdFile, grp_generic_tanh_double_s_fu_187_ap_ready, "grp_generic_tanh_double_s_fu_187_ap_ready");
    sc_trace(mVcdFile, grp_generic_tanh_double_s_fu_187_ap_done, "grp_generic_tanh_double_s_fu_187_ap_done");
    sc_trace(mVcdFile, Layer3_Neurons_CPU_address0, "Layer3_Neurons_CPU_address0");
    sc_trace(mVcdFile, Layer3_Neurons_CPU_ce0, "Layer3_Neurons_CPU_ce0");
    sc_trace(mVcdFile, Layer3_Neurons_CPU_we0, "Layer3_Neurons_CPU_we0");
    sc_trace(mVcdFile, Layer3_Neurons_CPU_q0, "Layer3_Neurons_CPU_q0");
    sc_trace(mVcdFile, Layer4_Neurons_CPU_address0, "Layer4_Neurons_CPU_address0");
    sc_trace(mVcdFile, Layer4_Neurons_CPU_ce0, "Layer4_Neurons_CPU_ce0");
    sc_trace(mVcdFile, Layer4_Neurons_CPU_we0, "Layer4_Neurons_CPU_we0");
    sc_trace(mVcdFile, grp_calculateLayer3_fu_157_ap_start, "grp_calculateLayer3_fu_157_ap_start");
    sc_trace(mVcdFile, grp_calculateLayer3_fu_157_ap_done, "grp_calculateLayer3_fu_157_ap_done");
    sc_trace(mVcdFile, grp_calculateLayer3_fu_157_ap_idle, "grp_calculateLayer3_fu_157_ap_idle");
    sc_trace(mVcdFile, grp_calculateLayer3_fu_157_ap_ready, "grp_calculateLayer3_fu_157_ap_ready");
    sc_trace(mVcdFile, grp_calculateLayer3_fu_157_Layer2_Neurons_CPU_address0, "grp_calculateLayer3_fu_157_Layer2_Neurons_CPU_address0");
    sc_trace(mVcdFile, grp_calculateLayer3_fu_157_Layer2_Neurons_CPU_ce0, "grp_calculateLayer3_fu_157_Layer2_Neurons_CPU_ce0");
    sc_trace(mVcdFile, grp_calculateLayer3_fu_157_Layer2_Neurons_CPU_address1, "grp_calculateLayer3_fu_157_Layer2_Neurons_CPU_address1");
    sc_trace(mVcdFile, grp_calculateLayer3_fu_157_Layer2_Neurons_CPU_ce1, "grp_calculateLayer3_fu_157_Layer2_Neurons_CPU_ce1");
    sc_trace(mVcdFile, grp_calculateLayer3_fu_157_Layer3_Neurons_CPU_address0, "grp_calculateLayer3_fu_157_Layer3_Neurons_CPU_address0");
    sc_trace(mVcdFile, grp_calculateLayer3_fu_157_Layer3_Neurons_CPU_ce0, "grp_calculateLayer3_fu_157_Layer3_Neurons_CPU_ce0");
    sc_trace(mVcdFile, grp_calculateLayer3_fu_157_Layer3_Neurons_CPU_we0, "grp_calculateLayer3_fu_157_Layer3_Neurons_CPU_we0");
    sc_trace(mVcdFile, grp_calculateLayer3_fu_157_Layer3_Neurons_CPU_d0, "grp_calculateLayer3_fu_157_Layer3_Neurons_CPU_d0");
    sc_trace(mVcdFile, grp_calculateLayer4_fu_173_ap_start, "grp_calculateLayer4_fu_173_ap_start");
    sc_trace(mVcdFile, grp_calculateLayer4_fu_173_ap_done, "grp_calculateLayer4_fu_173_ap_done");
    sc_trace(mVcdFile, grp_calculateLayer4_fu_173_ap_idle, "grp_calculateLayer4_fu_173_ap_idle");
    sc_trace(mVcdFile, grp_calculateLayer4_fu_173_ap_ready, "grp_calculateLayer4_fu_173_ap_ready");
    sc_trace(mVcdFile, grp_calculateLayer4_fu_173_Layer3_Neurons_CPU_address0, "grp_calculateLayer4_fu_173_Layer3_Neurons_CPU_address0");
    sc_trace(mVcdFile, grp_calculateLayer4_fu_173_Layer3_Neurons_CPU_ce0, "grp_calculateLayer4_fu_173_Layer3_Neurons_CPU_ce0");
    sc_trace(mVcdFile, grp_calculateLayer4_fu_173_Layer4_Neurons_CPU_address0, "grp_calculateLayer4_fu_173_Layer4_Neurons_CPU_address0");
    sc_trace(mVcdFile, grp_calculateLayer4_fu_173_Layer4_Neurons_CPU_ce0, "grp_calculateLayer4_fu_173_Layer4_Neurons_CPU_ce0");
    sc_trace(mVcdFile, grp_calculateLayer4_fu_173_Layer4_Neurons_CPU_we0, "grp_calculateLayer4_fu_173_Layer4_Neurons_CPU_we0");
    sc_trace(mVcdFile, grp_calculateLayer4_fu_173_Layer4_Neurons_CPU_d0, "grp_calculateLayer4_fu_173_Layer4_Neurons_CPU_d0");
    sc_trace(mVcdFile, grp_generic_tanh_double_s_fu_187_ap_start, "grp_generic_tanh_double_s_fu_187_ap_start");
    sc_trace(mVcdFile, grp_generic_tanh_double_s_fu_187_ap_idle, "grp_generic_tanh_double_s_fu_187_ap_idle");
    sc_trace(mVcdFile, i_0_i_reg_112, "i_0_i_reg_112");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, ap_CS_fsm_state33, "ap_CS_fsm_state33");
    sc_trace(mVcdFile, phi_mul_reg_124, "phi_mul_reg_124");
    sc_trace(mVcdFile, somme_0_i_reg_136, "somme_0_i_reg_136");
    sc_trace(mVcdFile, j_0_i_reg_146, "j_0_i_reg_146");
    sc_trace(mVcdFile, grp_calculateLayer3_fu_157_ap_start_reg, "grp_calculateLayer3_fu_157_ap_start_reg");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, grp_calculateLayer4_fu_173_ap_start_reg, "grp_calculateLayer4_fu_173_ap_start_reg");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, grp_generic_tanh_double_s_fu_187_ap_start_reg, "grp_generic_tanh_double_s_fu_187_ap_start_reg");
    sc_trace(mVcdFile, ap_CS_fsm_state25, "ap_CS_fsm_state25");
    sc_trace(mVcdFile, zext_ln58_fu_241_p1, "zext_ln58_fu_241_p1");
    sc_trace(mVcdFile, zext_ln60_fu_268_p1, "zext_ln60_fu_268_p1");
    sc_trace(mVcdFile, zext_ln60_1_fu_273_p1, "zext_ln60_1_fu_273_p1");
    sc_trace(mVcdFile, zext_ln61_fu_278_p1, "zext_ln61_fu_278_p1");
    sc_trace(mVcdFile, grp_fu_198_p0, "grp_fu_198_p0");
    sc_trace(mVcdFile, grp_fu_198_p1, "grp_fu_198_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state19, "ap_CS_fsm_state19");
    sc_trace(mVcdFile, ap_CS_fsm_state27, "ap_CS_fsm_state27");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, zext_ln60_2_fu_258_p1, "zext_ln60_2_fu_258_p1");
    sc_trace(mVcdFile, add_ln60_1_fu_262_p2, "add_ln60_1_fu_262_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("nerons.hdltvin.dat");
    mHdltvoutHandle.open("nerons.hdltvout.dat");
}

nerons::~nerons() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete Layer4_Weights_CPU_U;
    delete Layer3_Neurons_CPU_U;
    delete Layer4_Neurons_CPU_U;
    delete grp_calculateLayer3_fu_157;
    delete grp_calculateLayer4_fu_173;
    delete grp_generic_tanh_double_s_fu_187;
    delete nerons_dmul_64ns_64ns_64_6_max_dsp_1_U46;
    delete nerons_hadd_16ns_16ns_16_5_full_dsp_1_U47;
    delete nerons_hmul_16ns_16ns_16_4_max_dsp_1_U48;
    delete nerons_hptodp_16ns_64_2_1_U49;
}

void nerons::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void nerons::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_calculateLayer3_fu_157_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            grp_calculateLayer3_fu_157_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_calculateLayer3_fu_157_ap_ready.read())) {
            grp_calculateLayer3_fu_157_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_calculateLayer4_fu_173_ap_start_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
            grp_calculateLayer4_fu_173_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_calculateLayer4_fu_173_ap_ready.read())) {
            grp_calculateLayer4_fu_173_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_generic_tanh_double_s_fu_187_ap_start_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state25.read())) {
            grp_generic_tanh_double_s_fu_187_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_generic_tanh_double_s_fu_187_ap_ready.read())) {
            grp_generic_tanh_double_s_fu_187_ap_start_reg = ap_const_logic_0;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state33.read())) {
        i_0_i_reg_112 = i_reg_291.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(grp_calculateLayer4_fu_173_ap_done.read(), ap_const_logic_1))) {
        i_0_i_reg_112 = ap_const_lv4_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        j_0_i_reg_146 = j_reg_309.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        j_0_i_reg_146 = ap_const_lv7_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state33.read())) {
        phi_mul_reg_124 = add_ln57_reg_283.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(grp_calculateLayer4_fu_173_ap_done.read(), ap_const_logic_1))) {
        phi_mul_reg_124 = ap_const_lv10_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        somme_0_i_reg_136 = grp_fu_204_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        somme_0_i_reg_136 = Layer4_Weights_CPU_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        Layer4_Neurons_CPU_l_reg_329 = Layer4_Neurons_CPU_q0.read();
        Layer4_Weights_CPU_l_reg_324 = Layer4_Weights_CPU_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        add_ln57_reg_283 = add_ln57_fu_223_p2.read();
        i_reg_291 = i_fu_235_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        j_reg_309 = j_fu_252_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state24.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state32.read()))) {
        reg_217 = grp_fu_198_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        tmp_3_i_reg_334 = grp_fu_209_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read()) && esl_seteq<1,1,1>(grp_generic_tanh_double_s_fu_187_ap_done.read(), ap_const_logic_1))) {
        tmp_i_i_reg_349 = grp_generic_tanh_double_s_fu_187_ap_return.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        tmp_i_reg_344 = grp_fu_213_p1.read();
    }
}

void nerons::thread_Layer2_Neurons_CPU_address0() {
    Layer2_Neurons_CPU_address0 = grp_calculateLayer3_fu_157_Layer2_Neurons_CPU_address0.read();
}

void nerons::thread_Layer2_Neurons_CPU_address1() {
    Layer2_Neurons_CPU_address1 = grp_calculateLayer3_fu_157_Layer2_Neurons_CPU_address1.read();
}

void nerons::thread_Layer2_Neurons_CPU_ce0() {
    Layer2_Neurons_CPU_ce0 = grp_calculateLayer3_fu_157_Layer2_Neurons_CPU_ce0.read();
}

void nerons::thread_Layer2_Neurons_CPU_ce1() {
    Layer2_Neurons_CPU_ce1 = grp_calculateLayer3_fu_157_Layer2_Neurons_CPU_ce1.read();
}

void nerons::thread_Layer3_Neurons_CPU_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        Layer3_Neurons_CPU_address0 = grp_calculateLayer4_fu_173_Layer3_Neurons_CPU_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        Layer3_Neurons_CPU_address0 = grp_calculateLayer3_fu_157_Layer3_Neurons_CPU_address0.read();
    } else {
        Layer3_Neurons_CPU_address0 = "XXXXXXXXXXX";
    }
}

void nerons::thread_Layer3_Neurons_CPU_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        Layer3_Neurons_CPU_ce0 = grp_calculateLayer4_fu_173_Layer3_Neurons_CPU_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        Layer3_Neurons_CPU_ce0 = grp_calculateLayer3_fu_157_Layer3_Neurons_CPU_ce0.read();
    } else {
        Layer3_Neurons_CPU_ce0 = ap_const_logic_0;
    }
}

void nerons::thread_Layer3_Neurons_CPU_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        Layer3_Neurons_CPU_we0 = grp_calculateLayer3_fu_157_Layer3_Neurons_CPU_we0.read();
    } else {
        Layer3_Neurons_CPU_we0 = ap_const_logic_0;
    }
}

void nerons::thread_Layer4_Neurons_CPU_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        Layer4_Neurons_CPU_address0 =  (sc_lv<7>) (zext_ln60_1_fu_273_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        Layer4_Neurons_CPU_address0 = grp_calculateLayer4_fu_173_Layer4_Neurons_CPU_address0.read();
    } else {
        Layer4_Neurons_CPU_address0 =  (sc_lv<7>) ("XXXXXXX");
    }
}

void nerons::thread_Layer4_Neurons_CPU_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        Layer4_Neurons_CPU_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        Layer4_Neurons_CPU_ce0 = grp_calculateLayer4_fu_173_Layer4_Neurons_CPU_ce0.read();
    } else {
        Layer4_Neurons_CPU_ce0 = ap_const_logic_0;
    }
}

void nerons::thread_Layer4_Neurons_CPU_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        Layer4_Neurons_CPU_we0 = grp_calculateLayer4_fu_173_Layer4_Neurons_CPU_we0.read();
    } else {
        Layer4_Neurons_CPU_we0 = ap_const_logic_0;
    }
}

void nerons::thread_Layer4_Weights_CPU_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        Layer4_Weights_CPU_address0 =  (sc_lv<10>) (zext_ln60_fu_268_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        Layer4_Weights_CPU_address0 =  (sc_lv<10>) (zext_ln58_fu_241_p1.read());
    } else {
        Layer4_Weights_CPU_address0 =  (sc_lv<10>) ("XXXXXXXXXX");
    }
}

void nerons::thread_Layer4_Weights_CPU_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()))) {
        Layer4_Weights_CPU_ce0 = ap_const_logic_1;
    } else {
        Layer4_Weights_CPU_ce0 = ap_const_logic_0;
    }
}

void nerons::thread_Layer5_Neurons_CPU_address0() {
    Layer5_Neurons_CPU_address0 =  (sc_lv<4>) (zext_ln61_fu_278_p1.read());
}

void nerons::thread_Layer5_Neurons_CPU_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state33.read())) {
        Layer5_Neurons_CPU_ce0 = ap_const_logic_1;
    } else {
        Layer5_Neurons_CPU_ce0 = ap_const_logic_0;
    }
}

void nerons::thread_Layer5_Neurons_CPU_d0() {
    Layer5_Neurons_CPU_d0 = reg_217.read();
}

void nerons::thread_Layer5_Neurons_CPU_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state33.read())) {
        Layer5_Neurons_CPU_we0 = ap_const_logic_1;
    } else {
        Layer5_Neurons_CPU_we0 = ap_const_logic_0;
    }
}

void nerons::thread_add_ln57_fu_223_p2() {
    add_ln57_fu_223_p2 = (!phi_mul_reg_124.read().is_01() || !ap_const_lv10_65.is_01())? sc_lv<10>(): (sc_biguint<10>(phi_mul_reg_124.read()) + sc_biguint<10>(ap_const_lv10_65));
}

void nerons::thread_add_ln60_1_fu_262_p2() {
    add_ln60_1_fu_262_p2 = (!zext_ln60_2_fu_258_p1.read().is_01() || !phi_mul_reg_124.read().is_01())? sc_lv<10>(): (sc_biguint<10>(zext_ln60_2_fu_258_p1.read()) + sc_biguint<10>(phi_mul_reg_124.read()));
}

void nerons::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void nerons::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void nerons::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void nerons::thread_ap_CS_fsm_state17() {
    ap_CS_fsm_state17 = ap_CS_fsm.read()[16];
}

void nerons::thread_ap_CS_fsm_state18() {
    ap_CS_fsm_state18 = ap_CS_fsm.read()[17];
}

void nerons::thread_ap_CS_fsm_state19() {
    ap_CS_fsm_state19 = ap_CS_fsm.read()[18];
}

void nerons::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void nerons::thread_ap_CS_fsm_state24() {
    ap_CS_fsm_state24 = ap_CS_fsm.read()[23];
}

void nerons::thread_ap_CS_fsm_state25() {
    ap_CS_fsm_state25 = ap_CS_fsm.read()[24];
}

void nerons::thread_ap_CS_fsm_state26() {
    ap_CS_fsm_state26 = ap_CS_fsm.read()[25];
}

void nerons::thread_ap_CS_fsm_state27() {
    ap_CS_fsm_state27 = ap_CS_fsm.read()[26];
}

void nerons::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void nerons::thread_ap_CS_fsm_state32() {
    ap_CS_fsm_state32 = ap_CS_fsm.read()[31];
}

void nerons::thread_ap_CS_fsm_state33() {
    ap_CS_fsm_state33 = ap_CS_fsm.read()[32];
}

void nerons::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void nerons::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void nerons::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void nerons::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void nerons::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void nerons::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void nerons::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(icmp_ln57_fu_229_p2.read(), ap_const_lv1_1))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void nerons::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void nerons::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(icmp_ln57_fu_229_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void nerons::thread_grp_calculateLayer3_fu_157_ap_start() {
    grp_calculateLayer3_fu_157_ap_start = grp_calculateLayer3_fu_157_ap_start_reg.read();
}

void nerons::thread_grp_calculateLayer4_fu_173_ap_start() {
    grp_calculateLayer4_fu_173_ap_start = grp_calculateLayer4_fu_173_ap_start_reg.read();
}

void nerons::thread_grp_fu_198_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state27.read())) {
        grp_fu_198_p0 = tmp_i_i_reg_349.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        grp_fu_198_p0 = tmp_i_reg_344.read();
    } else {
        grp_fu_198_p0 =  (sc_lv<64>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void nerons::thread_grp_fu_198_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state27.read())) {
        grp_fu_198_p1 = ap_const_lv64_3FFB74538EF34D6A;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        grp_fu_198_p1 = ap_const_lv64_3FE55555571F7693;
    } else {
        grp_fu_198_p1 =  (sc_lv<64>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void nerons::thread_grp_generic_tanh_double_s_fu_187_ap_start() {
    grp_generic_tanh_double_s_fu_187_ap_start = grp_generic_tanh_double_s_fu_187_ap_start_reg.read();
}

void nerons::thread_i_fu_235_p2() {
    i_fu_235_p2 = (!i_0_i_reg_112.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(i_0_i_reg_112.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void nerons::thread_icmp_ln57_fu_229_p2() {
    icmp_ln57_fu_229_p2 = (!i_0_i_reg_112.read().is_01() || !ap_const_lv4_A.is_01())? sc_lv<1>(): sc_lv<1>(i_0_i_reg_112.read() == ap_const_lv4_A);
}

void nerons::thread_icmp_ln59_fu_246_p2() {
    icmp_ln59_fu_246_p2 = (!j_0_i_reg_146.read().is_01() || !ap_const_lv7_64.is_01())? sc_lv<1>(): sc_lv<1>(j_0_i_reg_146.read() == ap_const_lv7_64);
}

void nerons::thread_j_fu_252_p2() {
    j_fu_252_p2 = (!j_0_i_reg_146.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(j_0_i_reg_146.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void nerons::thread_zext_ln58_fu_241_p1() {
    zext_ln58_fu_241_p1 = esl_zext<64,10>(phi_mul_reg_124.read());
}

void nerons::thread_zext_ln60_1_fu_273_p1() {
    zext_ln60_1_fu_273_p1 = esl_zext<64,7>(j_0_i_reg_146.read());
}

void nerons::thread_zext_ln60_2_fu_258_p1() {
    zext_ln60_2_fu_258_p1 = esl_zext<10,7>(j_fu_252_p2.read());
}

void nerons::thread_zext_ln60_fu_268_p1() {
    zext_ln60_fu_268_p1 = esl_zext<64,10>(add_ln60_1_fu_262_p2.read());
}

void nerons::thread_zext_ln61_fu_278_p1() {
    zext_ln61_fu_278_p1 = esl_zext<64,4>(i_0_i_reg_112.read());
}

void nerons::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(grp_calculateLayer3_fu_157_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(grp_calculateLayer4_fu_173_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(icmp_ln57_fu_229_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(icmp_ln59_fu_246_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state18;
            } else {
                ap_NS_fsm = ap_ST_fsm_state8;
            }
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state19;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_fsm_state20;
            break;
        case 524288 : 
            ap_NS_fsm = ap_ST_fsm_state21;
            break;
        case 1048576 : 
            ap_NS_fsm = ap_ST_fsm_state22;
            break;
        case 2097152 : 
            ap_NS_fsm = ap_ST_fsm_state23;
            break;
        case 4194304 : 
            ap_NS_fsm = ap_ST_fsm_state24;
            break;
        case 8388608 : 
            ap_NS_fsm = ap_ST_fsm_state25;
            break;
        case 16777216 : 
            ap_NS_fsm = ap_ST_fsm_state26;
            break;
        case 33554432 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read()) && esl_seteq<1,1,1>(grp_generic_tanh_double_s_fu_187_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state27;
            } else {
                ap_NS_fsm = ap_ST_fsm_state26;
            }
            break;
        case 67108864 : 
            ap_NS_fsm = ap_ST_fsm_state28;
            break;
        case 134217728 : 
            ap_NS_fsm = ap_ST_fsm_state29;
            break;
        case 268435456 : 
            ap_NS_fsm = ap_ST_fsm_state30;
            break;
        case 536870912 : 
            ap_NS_fsm = ap_ST_fsm_state31;
            break;
        case 1073741824 : 
            ap_NS_fsm = ap_ST_fsm_state32;
            break;
        case 2147483648 : 
            ap_NS_fsm = ap_ST_fsm_state33;
            break;
        case 4294967296 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<33>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
            break;
    }
}

void nerons::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"Layer2_Neurons_CPU_address0\" :  \"" << Layer2_Neurons_CPU_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"Layer2_Neurons_CPU_ce0\" :  \"" << Layer2_Neurons_CPU_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"Layer2_Neurons_CPU_q0\" :  \"" << Layer2_Neurons_CPU_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"Layer2_Neurons_CPU_address1\" :  \"" << Layer2_Neurons_CPU_address1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"Layer2_Neurons_CPU_ce1\" :  \"" << Layer2_Neurons_CPU_ce1.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"Layer2_Neurons_CPU_q1\" :  \"" << Layer2_Neurons_CPU_q1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"Layer5_Neurons_CPU_address0\" :  \"" << Layer5_Neurons_CPU_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"Layer5_Neurons_CPU_ce0\" :  \"" << Layer5_Neurons_CPU_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"Layer5_Neurons_CPU_we0\" :  \"" << Layer5_Neurons_CPU_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"Layer5_Neurons_CPU_d0\" :  \"" << Layer5_Neurons_CPU_d0.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

