# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/led_constraints.xdc

# Block Designs: bd/led_test/led_test.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==led_test || ORIG_REF_NAME==led_test} -quiet] -quiet

# IP: bd/led_test/ip/led_test_led_controller_0_1/led_test_led_controller_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==led_test_led_controller_0_1 || ORIG_REF_NAME==led_test_led_controller_0_1} -quiet] -quiet

# IP: bd/led_test/ip/led_test_processing_system7_0_0/led_test_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==led_test_processing_system7_0_0 || ORIG_REF_NAME==led_test_processing_system7_0_0} -quiet] -quiet

# IP: bd/led_test/ip/led_test_ps7_0_axi_periph_0/led_test_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==led_test_ps7_0_axi_periph_0 || ORIG_REF_NAME==led_test_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/led_test/ip/led_test_rst_ps7_0_102M_0/led_test_rst_ps7_0_102M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==led_test_rst_ps7_0_102M_0 || ORIG_REF_NAME==led_test_rst_ps7_0_102M_0} -quiet] -quiet

# IP: bd/led_test/ip/led_test_auto_pc_0/led_test_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==led_test_auto_pc_0 || ORIG_REF_NAME==led_test_auto_pc_0} -quiet] -quiet

# XDC: bd/led_test/led_test_ooc.xdc
